/**
 * Legal document content (Terms, Privacy, Refunds). These are sensible,
 * well-structured STARTING TEMPLATES with clearly-marked placeholders
 * ([Company Legal Name], [Jurisdiction], [Address]). They are NOT legal advice —
 * have them reviewed by a qualified lawyer and your details filled in before
 * relying on them at launch.
 */

export type LegalSection = { heading: string; paragraphs?: string[]; bullets?: string[] };
export type LegalDoc = {
  key: "terms" | "privacy" | "refunds";
  title: string;
  updated: string;
  intro: string;
  sections: LegalSection[];
};

const UPDATED = "Last updated: 21 July 2026";
const COMPANY = "[Company Legal Name]";
const JURISDICTION = "[Jurisdiction / country of incorporation]";
const CONTACT = "support@ieltsace.com";

export const TERMS: LegalDoc = {
  key: "terms",
  title: "Terms of Use",
  updated: UPDATED,
  intro: `These Terms of Use govern your access to and use of IELTSAce (the "Service"), operated by ${COMPANY} ("we", "us"). By creating an account or using the Service, you agree to these terms.`,
  sections: [
    { heading: "1. Acceptance of terms", paragraphs: ["By accessing or using IELTSAce, you confirm that you have read, understood and agree to be bound by these Terms and our Privacy Policy. If you do not agree, do not use the Service."] },
    { heading: "2. Eligibility", paragraphs: ["You must be at least 16 years old, or the age of digital consent in your country, to use the Service. If you are under 18, you confirm you have permission from a parent or guardian."] },
    { heading: "3. Your account", bullets: ["Provide accurate information and keep it up to date.", "You are responsible for keeping your password secure and for all activity under your account.", "Accounts are for a single individual and may not be shared or transferred.", "Notify us promptly of any unauthorised use."] },
    { heading: "4. Acceptable use", paragraphs: ["You agree not to misuse the Service. In particular, you must not:"], bullets: ["Copy, scrape, resell, or redistribute practice content, questions or model answers.", "Share your account or provide access to others.", "Attempt to disrupt, reverse-engineer, or gain unauthorised access to the Service.", "Use the Service for any unlawful purpose."] },
    { heading: "5. Subscriptions, billing & renewals", paragraphs: ["Paid plans are billed in advance through our payment processor. Unless cancelled, subscriptions renew automatically at the end of each billing period at the then-current price. You can cancel at any time from your account settings; cancellation takes effect at the end of the current period. We may change prices with reasonable notice, effective from your next renewal."] },
    { heading: "6. AI scores and feedback", paragraphs: ["Band scores and feedback generated by our AI tools are automated estimates provided for practice and guidance only. They are not official IELTS results and do not guarantee any particular score on the actual exam. Your official band can only be awarded by the IELTS test partners."] },
    { heading: "7. Intellectual property", paragraphs: [`All content on the Service (excluding your own submissions) is owned by ${COMPANY} or its licensors and is protected by law. "IELTS" is a trademark of its respective owners; we are an independent platform and are not affiliated with or endorsed by them. You retain ownership of the answers you submit but grant us a licence to process them to provide and improve the Service.`] },
    { heading: "8. Disclaimers", paragraphs: ["The Service is provided \"as is\" and \"as available\" without warranties of any kind, whether express or implied, including fitness for a particular purpose. We do not warrant that the Service will be uninterrupted or error-free."] },
    { heading: "9. Limitation of liability", paragraphs: ["To the maximum extent permitted by law, we shall not be liable for any indirect, incidental or consequential damages, or for any loss of data, profits or exam outcomes arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim."] },
    { heading: "10. Termination", paragraphs: ["We may suspend or terminate your access if you breach these Terms. You may stop using the Service and delete your account at any time from your settings."] },
    { heading: "11. Changes to these terms", paragraphs: ["We may update these Terms from time to time. Material changes will be notified through the Service or by email. Continued use after changes take effect constitutes acceptance."] },
    { heading: "12. Governing law", paragraphs: [`These Terms are governed by the laws of ${JURISDICTION}, and any disputes shall be subject to the exclusive jurisdiction of its courts.`] },
    { heading: "13. Contact", paragraphs: [`Questions about these Terms? Email us at ${CONTACT}.`] },
  ],
};

export const PRIVACY: LegalDoc = {
  key: "privacy",
  title: "Privacy Policy",
  updated: UPDATED,
  intro: `This Privacy Policy explains how ${COMPANY} ("we") collects, uses and protects your personal data when you use IELTSAce.`,
  sections: [
    { heading: "1. Data we collect", bullets: ["Account data: your name, email address, and a securely hashed password.", "Study profile: target module, target band, exam date and country (optional).", "Practice data: your answers, including written responses and audio recordings, and the scores/feedback generated.", "Usage data: pages viewed and features used, to operate and improve the Service.", "Payment data: processed by our payment provider — we do not store your full card details."] },
    { heading: "2. How we use your data", bullets: ["To provide practice, mock tests and AI band scoring.", "To maintain your account, history and progress tracking.", "To process payments and manage subscriptions.", "To improve the Service and provide support.", "To send essential service emails (and, only with consent, product updates)."] },
    { heading: "3. Third-party processors", paragraphs: ["We share data with trusted service providers only as needed to run the Service:"], bullets: ["Cloud hosting and database providers (to run the platform).", "Amazon Web Services (S3) — to store Speaking audio recordings.", "SpeechSuper — to generate Speaking band scores from your audio.", "Google (Gemini) — to generate Writing band scores from your text.", "Our payment processor — to handle billing.", "These providers process data under their own terms; we share only what is necessary."] },
    { heading: "4. Cookies & sessions", paragraphs: ["We use a strictly-necessary session cookie to keep you signed in. We do not use advertising cookies. The session token is stored only as a hash on our servers."] },
    { heading: "5. Data retention", paragraphs: ["We keep your data while your account is active. If you delete your account, your personal data and practice history are permanently removed, subject to any retention required by law."] },
    { heading: "6. Your rights", paragraphs: ["Depending on your location, you may have the right to access, correct, export or delete your personal data, and to object to or restrict certain processing. You can update your profile or permanently delete your account from your settings, or contact us to exercise any right."] },
    { heading: "7. Security", paragraphs: ["We use industry-standard measures including password hashing, encrypted connections and access controls. No system is perfectly secure, but we work to protect your data and will notify you of any breach as required by law."] },
    { heading: "8. Children", paragraphs: ["The Service is not directed at children under 16, and we do not knowingly collect their data."] },
    { heading: "9. International transfers", paragraphs: ["Your data may be processed in countries other than your own. Where required, we put appropriate safeguards in place for such transfers."] },
    { heading: "10. Changes & contact", paragraphs: [`We may update this policy and will notify you of material changes. For any privacy request, email ${CONTACT}.`] },
  ],
};

export const REFUNDS: LegalDoc = {
  key: "refunds",
  title: "Refund Policy",
  updated: UPDATED,
  intro: "We want you to be confident in IELTSAce. This policy explains when refunds are available and how to request one.",
  sections: [
    { heading: "1. Free plan", paragraphs: ["Our free plan lets you try core features before paying, so you can decide whether IELTSAce is right for you at no cost."] },
    { heading: "2. Subscription refunds", paragraphs: ["If you are not satisfied with a paid subscription, you may request a full refund within 7 days of your initial purchase, provided you have made only limited use of the paid features (as a guide, fewer than 3 AI-scored evaluations or 1 mock test). Refunds are issued to your original payment method."] },
    { heading: "3. How to request a refund", paragraphs: [`Email ${CONTACT} from your account email address within the eligibility window, stating your reason. We aim to process eligible refunds within 5–10 business days.`] },
    { heading: "4. Non-refundable items", bullets: ["Subscriptions after the 7-day window or after substantial use of paid features.", "Renewal charges (cancel before renewal to avoid these — see below).", "Any one-off items explicitly marked non-refundable at purchase."] },
    { heading: "5. Cancellations", paragraphs: ["You can cancel auto-renewal at any time from your account settings. You will keep access until the end of the current billing period, and you will not be charged again."] },
    { heading: "6. Statutory rights", paragraphs: ["Nothing in this policy affects any refund or cancellation rights you have under the consumer law of your country, which may provide additional protections."] },
    { heading: "7. Contact", paragraphs: [`Questions about a refund? Email ${CONTACT}.`] },
  ],
};

export const LEGAL_BY_KEY = { terms: TERMS, privacy: PRIVACY, refunds: REFUNDS } as const;
