apps:
  - name: ielts
    cwd: .
    script: node_modules/next/dist/bin/next
    args: start -H 127.0.0.1 -p 3000
    node_args: --env-file=.env
    exec_mode: fork
    instances: 1
    autorestart: false
    max_memory_restart: 1G
    env:
      NODE_ENV: production
    out_file: ./logs/out.log
    error_file: ./logs/error.log
    merge_logs: true
    time: true
